// flow-typed signature: 29d4f9a8d91b8603687dca2b254e4a7d
// flow-typed version: <<STUB>>/babel-preset-es2015-rollup_v^3.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-es2015-rollup/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-es2015-rollup/index' {
  declare module.exports: $Exports<'babel-preset-es2015-rollup'>;
}
declare module 'babel-preset-es2015-rollup/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-rollup'>;
}
declare module 'babel-preset-es2015-rollup/test.js' {
  declare module.exports: $Exports<'babel-preset-es2015-rollup/test'>;
}
