export const inputRangeWrap: string;
export const inputRangePercent: string;
export const inputMultiRangeLabel: string;
export const inputMultiRange: string;
export const isNotSelected: string;
export const isSelected: string;
export const inputMultiRangeTrack: string;
export const inputMultiRangeFill: string;
export const inputRangeSmall: string;
