export const textareaWrap: string;
export const textareaLabel: string;
export const textareaInfo: string;
export const textareaTooltip: string;
export const isRequired: string;
export const isFocused: string;
export const hasValue: string;
export const isDisabled: string;
export const isError: string;
