enum Color {
  None = '',
  SgBlue = 'sg-blue',
  Slate = 'slate',
  RonBurundy = 'ron-burgundy',
  BurntOrange = 'burnt-orange',
  Carrot = 'carrot',
  Mango = 'mango',
  Mantis = 'mantis',
  Spruce = 'spruce',
  GrassStain = 'grass-stain',
  Lime = 'lime',
  Cobalt = 'cobalt',
  BlueBird = 'bluebird',
  SeaFoam = 'seafoam',
  Caribbean = 'caribbean',
  Crown = 'crown',
  Screample = 'screample',
  Sangria = 'sangria',
  Lavender = 'lavender',
  WildStrawberry = 'wild-strawberry',
  Steel = 'steel',
}

export default Color
